export const CATEGORY_ADD_REQUEST='CATEGORY_ADD_REQUEST'
export const CATEGORY_ADD_SUCCESS='CATEGORY_ADD_SUCCESS'
export const CATEGORY_ADD_FAIL='CATEGORY_ADD_FAIL'
export const CATEGORY_ADD_RESET='CATEGORY_ADD_RESET'

export const CATEGORY_FETCH_REQUEST='CATEGORY_FETCH_REQUEST'
export const CATEGORY_FETCH_SUCCESS='CATEGORY_FETCH_SUCCESS'
export const CATEGORY_FETCH_FAIL='CATEGORY_FETCH_FAIL'
export const CATEGORY_FETCH_RESET='CATEGORY_FETCH_RESET'

export const CATEGORY_UPDATE_REQUEST='CATEGORY_FETCH_REQUEST'
export const CATEGORY_UPDATE_SUCCESS='CATEGORY_FETCH_SUCCESS'
export const CATEGORY_UPDATE_FAIL='CATEGORY_FETCH_FAIL'
export const CATEGORY_UPDATE_RESET='CATEGORY_FETCH_RESET'

export const CATEGORY_DELETE_REQUEST='CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS='CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAIL='CATEGORY_DELETE_FAIL'
export const CATEGORY_DELETE_RESET='CATEGORY_DELETE_RESET'