export const PRODUCT_ADD_REQUEST='PRODUCT_ADD_REQUEST'
export const PRODUCT_ADD_SUCCESS='PRODUCT_ADD_SUCCESS'
export const PRODUCT_ADD_FAIL='PRODUCT_ADD_FAIL'
export const PRODUCT_ADD_RESET='PRODUCT_ADD_RESET'

export const PRODUCT_FETCH_REQUEST='PRODUCT_FETCH_REQUEST'
export const PRODUCT_FETCH_SUCCESS='PRODUCT_FETCH_SUCCESS'
export const PRODUCT_FETCH_FAIL='PRODUCT_FETCH_FAIL'
export const PRODUCT_FETCH_RESET='PRODUCT_FETCH_RESET'

export const PRODUCT_UPDATE_REQUEST='PRODUCT_FETCH_REQUEST'
export const PRODUCT_UPDATE_SUCCESS='PRODUCT_FETCH_SUCCESS'
export const PRODUCT_UPDATE_FAIL='PRODUCT_FETCH_FAIL'
export const PRODUCT_UPDATE_RESET='PRODUCT_FETCH_RESET'

export const PRODUCT_DELETE_REQUEST='PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS='PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL='PRODUCT_DELETE_FAIL'
export const PRODUCT_DELETE_RESET='PRODUCT_DELETE_RESET'